#
# This Makefile was generated by Code::Blocks IDE.
#

SRCS_f90d1 = \
m_multislice.f90 \
m_string.f90 \
m_tilt.f90 \
m_user_input.f90 \
m_crystallography.f90 \
MS_utilities.f90 \
mod_global_variables.f90 \
m_electron.f90 \
fftw_wrapper.f90 \
mod_output.f90 \
muSTEM.f90 \
quadpack.f90 \
m_absorption.f90 \
s_absorptive_stem.f90 \
m_lens.f90 \
s_absorptive_tem.f90 \
m_numerical_tools.f90 \
s_qep_stem.f90 \
m_potential.f90 \
s_qep_tem.f90 \
m_precision.f90 

OBJS_f90d1 = \
m_multislice.o \
m_string.o \
m_tilt.o \
m_user_input.o \
m_crystallography.o \
MS_utilities.o \
mod_global_variables.o \
m_electron.o \
fftw_wrapper.o \
mod_output.o \
muSTEM.o \
quadpack.o \
m_absorption.o \
s_absorptive_stem.o \
m_lens.o \
s_absorptive_tem.o \
m_numerical_tools.o \
s_qep_stem.o \
m_potential.o \
s_qep_tem.o \
m_precision.o 

SRC_DIR_f90d1 = Source/
OBJS_DIR = obj/Release/Source/
EXE_DIR = bin/Release/

EXE = muSTEM.exe
FC = gfortran.exe
LD = gfortran.exe
IDIR = -IC:\Program Files\mingw-w64\fftw-3.3.5-dll64 
CFLAGS = -Wall -Dsingle_precision -O2 -cpp -fopenmp  -J$(OBJS_DIR) $(IDIR)
LFLAGS = -s -fopenmp 
LIBS = -l\libfftw3-3.dll -l\libfftw3f-3.dll 

VPATH = $(SRC_DIR_f90d1):$(OBJS_DIR)
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_f90d1))

all : $(EXE)

$(EXE) : $(OBJS_f90d1)
	@mkdir -p $(EXE_DIR)
	$(LD) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJS_f90d1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d1)$(@:.o=.f90) -o $(OBJS_DIR)$@

clean :
	rm -f $(OBJS_DIR)*.*
	rm -f $(EXE_DIR)$(EXE)

# Dependencies of files
m_multislice.o: \
    m_multislice.f90 \
    fftw_wrapper.o \
    mod_global_variables.o \
    m_crystallography.o \
    m_numerical_tools.o \
    m_precision.o \
    m_string.o \
    m_user_input.o \
    mod_output.o
m_string.o: \
    m_string.f90 \
    m_precision.o
m_tilt.o: \
    m_tilt.f90 \
    mod_global_variables.o \
    m_crystallography.o \
    m_precision.o \
    m_string.o \
    m_user_input.o
m_user_input.o: \
    m_user_input.f90 \
    m_precision.o \
    m_string.o
m_crystallography.o: \
    m_crystallography.f90 \
    mod_global_variables.o \
    m_precision.o
MS_utilities.o: \
    MS_utilities.f90 \
    fftw_wrapper.o \
    mod_global_variables.o \
    m_crystallography.o \
    m_electron.o \
    m_lens.o \
    m_multislice.o \
    m_potential.o \
    m_precision.o \
    m_string.o \
    m_user_input.o \
    mod_output.o
mod_global_variables.o: \
    mod_global_variables.f90 \
    m_precision.o
m_electron.o: \
    m_electron.f90 \
    m_precision.o
fftw_wrapper.o: \
    fftw_wrapper.f90
mod_output.o: \
    mod_output.f90 \
    fftw_wrapper.o \
    mod_global_variables.o \
    m_precision.o \
    m_string.o \
    m_user_input.o
muSTEM.o: \
    muSTEM.f90 \
    mod_global_variables.o \
    m_absorption.o \
    m_electron.o \
    m_lens.o \
    m_multislice.o \
    m_potential.o \
    m_string.o \
    m_tilt.o \
    m_user_input.o \
    mod_output.o
quadpack.o: \
    quadpack.f90
m_absorption.o: \
    m_absorption.f90 \
    mod_global_variables.o \
    m_crystallography.o \
    m_electron.o \
    m_numerical_tools.o \
    m_precision.o \
    m_string.o \
    m_user_input.o \
    mod_output.o \
    quadpack.o
s_absorptive_stem.o: \
    s_absorptive_stem.f90 \
    fftw_wrapper.o \
    mod_global_variables.o \
    m_absorption.o \
    m_crystallography.o \
    m_lens.o \
    m_multislice.o \
    m_potential.o \
    m_precision.o \
    m_string.o \
    m_tilt.o \
    mod_output.o
m_lens.o: \
    m_lens.f90 \
    fftw_wrapper.o \
    mod_global_variables.o \
    m_crystallography.o \
    m_multislice.o \
    m_precision.o \
    m_string.o \
    m_user_input.o \
    mod_output.o
s_absorptive_tem.o: \
    s_absorptive_tem.f90 \
    fftw_wrapper.o \
    mod_global_variables.o \
    m_absorption.o \
    m_lens.o \
    m_multislice.o \
    m_potential.o \
    m_precision.o \
    m_string.o \
    m_tilt.o \
    m_user_input.o \
    mod_output.o
m_numerical_tools.o: \
    m_numerical_tools.f90 \
    m_precision.o
s_qep_stem.o: \
    s_qep_stem.f90 \
    fftw_wrapper.o \
    mod_global_variables.o \
    m_crystallography.o \
    m_lens.o \
    m_multislice.o \
    m_numerical_tools.o \
    m_potential.o \
    m_precision.o \
    m_string.o \
    m_tilt.o \
    m_user_input.o \
    mod_output.o
m_potential.o: \
    m_potential.f90 \
    fftw_wrapper.o \
    mod_global_variables.o \
    m_absorption.o \
    m_crystallography.o \
    m_electron.o \
    m_multislice.o \
    m_numerical_tools.o \
    m_precision.o \
    m_string.o \
    m_user_input.o \
    mod_output.o
s_qep_tem.o: \
    s_qep_tem.f90 \
    fftw_wrapper.o \
    mod_global_variables.o \
    m_lens.o \
    m_multislice.o \
    m_numerical_tools.o \
    m_potential.o \
    m_precision.o \
    m_string.o \
    m_tilt.o \
    mod_output.o
m_precision.o: \
    m_precision.f90

